// Generated by scripts/gen-mod-data.sh: tests/fixtures with phi-scan.sh's counts. Do not edit.
export const FIXTURES: { name: string; text: string; counts: Record<string, Record<string, number>> }[] = [
  {
    name: "clean-code.diff",
    text: "diff --git a/app/jobs.ts b/app/jobs.ts\nindex a1b2c3d..e4f5a6b 100644\n--- a/app/jobs.ts\n+++ b/app/jobs.ts\n@@ -4,6 +4,8 @@ export const jobs = [\n   { id: \"3f2a9c1e-7b4d-4e8a-9c2f-5d6e7f8a9b0c\", runAt: \"2026-09-21T14:02:11Z\" },\n+  { id: \"b7e3d2c1-0a9f-4e8d-8c7b-6a5f4e3d2c1b\", runAt: \"2026-09-22T09:30:00.000Z\" },\n+  { id: \"0c9d8e7f-6a5b-4c3d-9e2f-1a0b9c8d7e6f\", runAt: \"2026-09-23T00:00:00+00:00\" },\n ];\n",
    counts: {
      default: {},
      diff: {},
      prose: {},
      diffAllow: {},
    },
  },
  {
    name: "clean-commit.diff",
    text: "commit 4c1e9a7b2d0f3e5a6b7c8d9e0f1a2b3c4d5e6f7a\nAuthor: Sample Dev <sample.dev@example.invalid>\nDate:   Mon Sep 21 14:02:11 2026 -0500\n\n    Retry the upload once on a timeout\n\n    Signed-off-by: Sample Dev <sample.dev@example.invalid>\n    Co-Authored-By: Helper Bot <helper.bot@example.invalid>\n\ndiff --git a/src/upload.sh b/src/upload.sh\nindex 3e4fa1c..9b0d2e7 100644\n--- a/src/upload.sh\n+++ b/src/upload.sh\n@@ -12,3 +12,4 @@ upload() {\n   curl -sS --fail \"$url\" -T \"$file\"\n+  curl -sS --fail --retry 1 \"$url\" -T \"$file\"\n }\n",
    counts: {
      default: {"email-address": 3},
      diff: {},
      prose: {"email-address": 3},
      diffAllow: {},
    },
  },
  {
    name: "clean-config.json",
    text: "{\n  \"service\": \"sample-api\",\n  \"port\": 8080,\n  \"timeout_ms\": 30000,\n  \"retries\": 3,\n  \"log_level\": \"info\",\n  \"features\": { \"cache\": true, \"batch_size\": 250 }\n}\n",
    counts: {
      default: {},
      diff: {},
      prose: {},
      diffAllow: {},
    },
  },
  {
    name: "clean-delegate.diff",
    text: "commit 7a2b9c4d1e0f3a5b6c7d8e9f0a1b2c3d4e5f6a7b\nAuthor: Delegate Bot <delegate.bot@example.invalid>\nDate:   Tue Sep 22 09:15:40 2026 -0500\n\n    phi-delegate: 01-task (auto-commit of delegated work)\n\ndiff --git a/seed.txt b/seed.txt\nindex 8f1c2d3..4b5e6a7 100644\n--- a/seed.txt\n+++ b/seed.txt\n@@ -1 +1,2 @@\n fixture seed\n+delegate wrote this\n",
    counts: {
      default: {"email-address": 1},
      diff: {},
      prose: {"email-address": 1},
      diffAllow: {},
    },
  },
  {
    name: "clean-log-p.diff",
    text: "commit 0587d0e771161526b50a3e4aef86c29e826264fe\nAuthor: Sample Dev <sample.dev@example.invalid>\nDate:   Mon Sep 28 10:00:00 2026 -0500\n\n    Raise the retry count\n    \n    Signed-off-by: Sample Dev <sample.dev@example.invalid>\n    Co-Authored-By: Helper Bot <helper.bot@example.invalid>\n\ndiff --git a/config.yml b/config.yml\nindex c802104..f59b320 100644\n--- a/config.yml\n+++ b/config.yml\n@@ -1 +1,2 @@\n-retries: 1\n+retries: 2\n+timeout_s: 30\n",
    counts: {
      default: {"email-address": 3},
      diff: {},
      prose: {"email-address": 3},
      diffAllow: {},
    },
  },
  {
    name: "clean-log.txt",
    text: "2026-09-21T14:02:11.482Z INFO  worker started pid=4121 queue=default\n2026-09-21T14:02:12.007Z INFO  job 3f2a9c1e-7b4d-4e8a-9c2f-5d6e7f8a9b0c picked up\n2026-09-21T14:02:13.915Z WARN  retrying request status=503 attempt=2 latency_ms=1840\n2026-09-21T14:02:15.120Z INFO  job finished rows=42 duration_ms=2913\n",
    counts: {
      default: {},
      diff: {},
      prose: {},
      diffAllow: {},
    },
  },
  {
    name: "clean-readme.md",
    text: "The scanner is a tripwire for protected health information. It looks for\nSSN and phone shapes, email addresses, dates, MRN and DOB keywords, patient\nname fields, diagnosis and prescription words, street addresses, and long\ndigit runs, then reports a count per class without printing the text.\n",
    counts: {
      default: {"dob-keyword": 1, "identifier-keyword": 1, "clinical-keyword": 1},
      diff: {"dob-keyword": 1, "identifier-keyword": 1, "clinical-keyword": 1},
      prose: {},
      diffAllow: {"dob-keyword": 1, "identifier-keyword": 1, "clinical-keyword": 1},
    },
  },
  {
    name: "dirty-clinical.txt",
    text: "Diagnosis code ICD-10 Z00.00, prescription refilled, MRN SYN0000123.\n",
    counts: {
      default: {"identifier-keyword": 1, "clinical-keyword": 1},
      diff: {"identifier-keyword": 1, "clinical-keyword": 1},
      prose: {},
      diffAllow: {"identifier-keyword": 1, "clinical-keyword": 1},
    },
  },
  {
    name: "dirty-contact.txt",
    text: "Callback 555-555-0142, lives at 100 Sample Street.\n",
    counts: {
      default: {"phone-shaped": 1, "street-address": 1},
      diff: {"phone-shaped": 1, "street-address": 1},
      prose: {"phone-shaped": 1, "street-address": 1},
      diffAllow: {"phone-shaped": 1, "street-address": 1},
    },
  },
  {
    name: "dirty-content.diff",
    text: "diff --git a/seed/contacts.csv b/seed/contacts.csv\nindex 1a2b3c4..5d6e7f8 100644\n--- a/seed/contacts.csv\n+++ b/seed/contacts.csv\n@@ -1,2 +1,3 @@\n id,contact\n+7,synthetic.person@example.invalid\n",
    counts: {
      default: {"email-address": 1},
      diff: {"email-address": 1},
      prose: {"email-address": 1},
      diffAllow: {},
    },
  },
  {
    name: "dirty-context-author.diff",
    text: "diff --git a/docs/CONTACTS.md b/docs/CONTACTS.md\nindex 2c3d4e5..6f7a8b9 100644\n--- a/docs/CONTACTS.md\n+++ b/docs/CONTACTS.md\n@@ -1,3 +1,3 @@\n # Contacts\n Author: someone@example.com\n-Reviewed: pending\n+Reviewed: done\n",
    counts: {
      default: {"email-address": 1},
      diff: {"email-address": 1},
      prose: {"email-address": 1},
      diffAllow: {"email-address": 1},
    },
  },
  {
    name: "dirty-cr-trailer.txt",
    text: "export row 1\n987-65-4320\rAuthor: fine\n",
    counts: {
      default: {"ssn-shaped": 1},
      diff: {"ssn-shaped": 1},
      prose: {"ssn-shaped": 1},
      diffAllow: {"ssn-shaped": 1},
    },
  },
  {
    name: "dirty-dob.txt",
    text: "Patient name: Test Person, date of birth 01/02/1970.\n",
    counts: {
      default: {"date-shaped": 1, "dob-keyword": 1, "patient-name-keyword": 1},
      diff: {"date-shaped": 1, "dob-keyword": 1, "patient-name-keyword": 1},
      prose: {"date-shaped": 1, "patient-name-keyword": 1},
      diffAllow: {"date-shaped": 1, "dob-keyword": 1, "patient-name-keyword": 1},
    },
  },
  {
    name: "dirty-hunk-author.diff",
    text: "commit 1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b\nAuthor: Sample Dev <sample.dev@example.invalid>\nDate:   Mon Sep 21 14:02:11 2026 -0500\n\n    Quote the release notes header\n\n    Signed-off-by: Sample Dev <sample.dev@example.invalid>\n\ndiff --git a/NOTES.md b/NOTES.md\nindex 3e4fa1c..9b0d2e7 100644\n--- a/NOTES.md\n+++ b/NOTES.md\n@@ -1,3 +1,4 @@\n Release notes\n    Author: pat.doe@example.org\n+Reviewed for release\n done\n",
    counts: {
      default: {"email-address": 3},
      diff: {"email-address": 1},
      prose: {"email-address": 3},
      diffAllow: {"email-address": 1},
    },
  },
  {
    name: "dirty-phone-paren.txt",
    text: "Callback (555) 555-0142 after the visit.\n",
    counts: {
      default: {"phone-shaped": 1},
      diff: {"phone-shaped": 1},
      prose: {"phone-shaped": 1},
      diffAllow: {"phone-shaped": 1},
    },
  },
  {
    name: "dirty-prose-ssn.md",
    text: "The scanner looks for a diagnosis word, a patient id, or a date of birth\nnear an identifier. For example, a synthetic record such as 987-65-4320\nin a note, or a callback number like 555-555-0187, must still be flagged\nwhen this page is scanned with the prose profile.\n",
    counts: {
      default: {"ssn-shaped": 1, "phone-shaped": 1, "dob-keyword": 1, "identifier-keyword": 1, "clinical-keyword": 1},
      diff: {"ssn-shaped": 1, "phone-shaped": 1, "dob-keyword": 1, "identifier-keyword": 1, "clinical-keyword": 1},
      prose: {"ssn-shaped": 1, "phone-shaped": 1},
      diffAllow: {"ssn-shaped": 1, "phone-shaped": 1, "dob-keyword": 1, "identifier-keyword": 1, "clinical-keyword": 1},
    },
  },
  {
    name: "dirty-ssn.txt",
    text: "Applicant record (synthetic): ssn 987-65-4320, status pending.\n",
    counts: {
      default: {"ssn-shaped": 1, "identifier-keyword": 1},
      diff: {"ssn-shaped": 1, "identifier-keyword": 1},
      prose: {"ssn-shaped": 1},
      diffAllow: {"ssn-shaped": 1, "identifier-keyword": 1},
    },
  },
  {
    name: "edge-nbsp.txt",
    text: "patient name : Sample\nsafe 987-65-4320\n",
    counts: {
      default: {"ssn-shaped": 1},
      diff: {"ssn-shaped": 1},
      prose: {"ssn-shaped": 1},
      diffAllow: {"ssn-shaped": 1},
    },
  },
  {
    name: "edge-unicode-street.txt",
    text: "Shipping label: 12 Kelvin Road\n",
    counts: {
      default: {},
      diff: {},
      prose: {},
      diffAllow: {},
    },
  },
]
export const ALLOW_ENTRIES = ["@example\\.invalid","safe\\s"]
