#!/usr/bin/env bash
# Generate the TypeScript copies the mod and its tests need, because a hooks
# module and `claude plugin test` cannot read files at load time:
#   hooks/patterns.generated.ts      scripts/phi-patterns.tsv as a string
#   tests/mod/parity.generated.ts    every fixture, with phi-scan.sh's
#                                    per-class counts under each profile
# With --check, write to a temp dir and fail if the committed copies differ.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCAN="$ROOT/scripts/phi-scan.sh"
PROFILES="default diff prose"
# Two allowlist cases ride along: diffAllow (--profile diff with
# ALLOW_ENTRIES) and edgeAllow (the default profile with EDGE_ENTRIES,
# constructs whose meaning differs between grep and JavaScript), one entry
# per line.
ALLOW_ENTRIES='@example\.invalid
safe\s'
EDGE_ENTRIES='[\s]
^.{12}$'

check=0
[ "${1:-}" = "--check" ] && check=1

# A file's exact bytes as a double-quoted TypeScript string literal.
ts_string() {
  local f="$1" body
  body="$(sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e "s/$(printf '\t')/\\\\t/g" -e "s/$(printf '\r')/\\\\r/g" "$f" \
    | awk 'NR > 1 { printf "\\n" } { printf "%s", $0 }')"
  if [ -n "$(tail -c 1 "$f")" ]; then printf '"%s"' "$body"; else printf '"%s\\n"' "$body"; fi
}

# phi-scan.sh's report as a TypeScript object of class -> line count.
ts_counts() {
  local f="$1"
  shift
  "$SCAN" "$@" "$f" 2>/dev/null \
    | awk 'BEGIN { printf "{" } /line\(s\)$/ { printf "%s\"%s\": %s", sep, $1, $2; sep = ", " } END { printf "}" }' \
    || true
}

write_patterns() {
  {
    echo "// Generated by scripts/gen-mod-data.sh from scripts/phi-patterns.tsv. Do not edit."
    printf 'export const PATTERNS_TSV = %s\n' "$(ts_string "$ROOT/scripts/phi-patterns.tsv")"
  } >"$1"
}

write_parity() {
  local f p allow edge
  allow="$(mktemp "${TMPDIR:-/tmp}/phi-gen-allow.XXXXXX")"
  edge="$(mktemp "${TMPDIR:-/tmp}/phi-gen-edge.XXXXXX")"
  printf '%s\n' "$ALLOW_ENTRIES" >"$allow"
  printf '%s\n' "$EDGE_ENTRIES" >"$edge"
  {
    echo "// Generated by scripts/gen-mod-data.sh: tests/fixtures with phi-scan.sh's counts. Do not edit."
    echo "export const FIXTURES: { name: string; text: string; counts: Record<string, Record<string, number>> }[] = ["
    for f in "$ROOT"/tests/fixtures/*; do
      printf '  {\n    name: "%s",\n    text: %s,\n    counts: {\n' "$(basename "$f")" "$(ts_string "$f")"
      for p in $PROFILES; do
        printf '      %s: %s,\n' "$p" "$(ts_counts "$f" --profile "$p")"
      done
      printf '      diffAllow: %s,\n' "$(ts_counts "$f" --profile diff --allow "$allow")"
      printf '      edgeAllow: %s,\n' "$(ts_counts "$f" --allow "$edge")"
      printf '    },\n  },\n'
    done
    echo "]"
    printf 'export const ALLOW_ENTRIES = [%s]\n' \
      "$(printf '%s\n' "$ALLOW_ENTRIES" | sed -e 's/\\/\\\\/g' -e 's/.*/"&"/' | paste -s -d, -)"
    printf 'export const EDGE_ENTRIES = [%s]\n' \
      "$(printf '%s\n' "$EDGE_ENTRIES" | sed -e 's/\\/\\\\/g' -e 's/.*/"&"/' | paste -s -d, -)"
  } >"$1"
  rm -f "$allow" "$edge"
}

if [ "$check" -eq 1 ]; then
  tmp="$(mktemp -d "${TMPDIR:-/tmp}/phi-gen.XXXXXX")"
  trap 'rm -rf "$tmp"' EXIT
  write_patterns "$tmp/patterns.ts"
  write_parity "$tmp/parity.ts"
  status=0
  cmp -s "$tmp/patterns.ts" "$ROOT/hooks/patterns.generated.ts" \
    || { echo "stale: hooks/patterns.generated.ts (run scripts/gen-mod-data.sh)"; status=1; }
  cmp -s "$tmp/parity.ts" "$ROOT/tests/mod/parity.generated.ts" \
    || { echo "stale: tests/mod/parity.generated.ts (run scripts/gen-mod-data.sh)"; status=1; }
  exit "$status"
fi

mkdir -p "$ROOT/tests/mod"
write_patterns "$ROOT/hooks/patterns.generated.ts"
write_parity "$ROOT/tests/mod/parity.generated.ts"
echo "wrote hooks/patterns.generated.ts and tests/mod/parity.generated.ts"
